version: '3.7'

services:
  client-app:
    container_name: go-client-app
    build:
      context: .
    command: sh -c "go mod download && make build_client && ./bin/client-bin"
    depends_on:
      - server-app
    volumes:
      - ./client:/opt/app/client
      - ./go.mod:/opt/app/go.mod
      - ./go.sum:/opt/app/go.sum
      - ./Makefile:/opt/app/Makefile
    ports:
      - 3000:3000
        
  server-app:
    container_name: go-server-app
    build:
      context: .
    command: sh -c "go mod download && make build_server && ./bin/server-bin"
    volumes:
      - ./server:/opt/app/server
      - ./go.mod:/opt/app/go.mod
      - ./go.sum:/opt/app/go.sum
      - ./Makefile:/opt/app/Makefile
    env_file:
      - ./.env
    ports:
      - 3100:3100