version: '3.7'

services:
  client-app:
    container_name: go-client-app
    build:
      context: .
    command: sh -c "go mod download && go build -o bin/app main.go && ./bin/app"
    depends_on:
      - server-app
    volumes:
      - ./client:/opt/app
    ports:
      - 3000:3000
        
  server-app:
    container_name: go-server-app
    build:
      context: .
    command: sh -c "go mod download && go build -o bin/app main.go && ./bin/app"
    volumes:
      - ./server:/opt/app
    ports:
      - 3100:3100