version: '3.7'

services:
  client-app:
    container_name: go-client-app
    build:
      context: .
    command: sh -c "make build_client && ./bin/client-bin"
    depends_on:
      - server-app
    volumes:
      - ./:/opt/app/
    env_file:
      - ./.env
        
  server-app:
    container_name: go-server-app
    build:
      context: .
    command: sh -c "make build_server && ./bin/server-bin"
    volumes:
      - ./:/opt/app/
    env_file:
      - ./.env
    ports:
      - 3100:3100